version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg:/usr/local/var/postgres/
  redis:
    image: redis
  web:
    build: .
    image: ducvan0212/portal:ver2.0
    env_file:
      - .env
    volumes:
      - .:/phylotastic-portal
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  pg: