# version: '3'
# services:
#   db:
#     image: postgres
#     env_file:
#       - .env
#     volumes:
#       - pg:/usr/local/var/postgres/
#   redis:
#     image: redis
#   web:
#     build: .
#     image: ducvan0212/portal:ver2.0
#     env_file:
#       - .env
#     volumes:
#       - .:/phylotastic-portal
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - redis
# volumes:
#   pg:
  
  
version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: portal_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/phylotastic-portal
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis