# version: '3'
# services:
#   db:
#     image: postgres
#     env_file:
#       - .env
#     volumes:
#       - pg:/usr/local/var/postgres/
#   redis:
#     image: redis
#   web:
#     build: .
#     image: ducvan0212/portal:ver2.0
#     env_file:
#       - .env
#     volumes:
#       - .:/phylotastic-portal
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - redis
# volumes:
#   pg:
  
  
version: '3'
services:
  db:
    image: postgres:9.4.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: portal_development
    # change /Users/... to location of the database file if you want to persist data
    # volumes:
#       - ./tmp/db:/Users/ndvan/Library/Application Support/Postgres/var-9.4
    ports:
      - "5432:5432"
  redis:
    image: redis
  web:
    # build: .
    image: ducvan0212/portal:2.1
    entrypoint: ./lib/init_db.sh
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/phylotastic-portal
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    # build: .
    # restart: always
    image: ducvan0212/portal:2.1
    command: 'bundle exec sidekiq'
    # volumes:
    #   - ../../:/myapp
    # environment:
    #   RAILS_ENV: "docker_development"
    #   REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis