development:
  adapter: redis
  # url: redis://localhost:6379/1
  url: redis://redis:6379/1

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: redis://redis:6379/1
  channel_prefix: phylotastic-portal_production
